# Generated by Django 4.2.9 on 2024-02-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='время выполнения привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='good_habit',
            field=models.BooleanField(default=False, verbose_name='полезная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='вознаграждение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(verbose_name='время'),
        ),
    ]
